import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Search, ChevronRight, Medal, ShoppingBag, Pencil, Trophy, PiggyBank, ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/store";
import { brl } from "@/lib/finance";
import { normalizeProductQuery, storeSearches } from "@/lib/ofertas";

export const Route=createFileRoute("/antes-de-comprar")({head:()=>({meta:[{title:"Antes de Comprar — MamaWise"}]}),component:Comprar});
const offers=[{name:"Mercado Livre",price:79.9,frete:9.9,total:89.8,days:2,icon:"🏅",color:"border-[#59bd8b] bg-[#f2fff8]"},{name:"Shopee",price:82.5,frete:6.9,total:89.4,days:3,icon:"🛍️",color:"border-border bg-white"},{name:"Magalu",price:89.9,frete:0,total:89.9,days:4,icon:"M",color:"border-border bg-white"}];
function Comprar(){const [step,setStep]=useState(1);const [query,setQuery]=useState("");const [product,setProduct]=useState("Fralda Pampers M - 80 unidades");const {data,addDeposit}=useStore();const economy=23.4;return <AppShell title={step===1?"Antes de Comprar":step===2?"Resultado da busca":"Análise da MamaWise"}>{step===1&&<SearchScreen query={query} setQuery={setQuery} onSearch={()=>{if(query.trim()){setProduct(query.trim());setStep(2)}}}/>} {step===2&&<Results product={product} onBack={()=>setStep(1)} onAnalysis={()=>setStep(3)}/>} {step===3&&<Analysis onBack={()=>setStep(2)} onSave={()=>{const b=data.boxes[0];if(b)addDeposit({boxId:b.id,amount:economy,date:new Date().toISOString().slice(0,10),note:`Economia de ${product}`})}}/>}</AppShell>}
function SearchScreen({query,setQuery,onSearch}:{query:string;setQuery:(v:string)=>void;onSearch:()=>void}){const suggestions=["Fralda Pampers M","Leite Nan 800g","Carrinho de bebê","Cadeira infantil","Lenço umedecido","Shampoo infantil"];return <><section className="rounded-2xl bg-[#f8fcff] p-4"><h2 className="text-[13px] font-bold leading-relaxed">Encontre a melhor oferta<br/>entre várias lojas</h2><p className="mt-5 text-[10px] font-medium">Pesquise o produto que você deseja:</p><div className="relative mt-2"><Input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&onSearch()} placeholder="Ex.: fralda Pampers M" className="h-11 rounded-xl bg-white pr-10 text-[10px]"/><button onClick={onSearch} className="absolute right-2 top-1/2 -translate-y-1/2"><Search className="size-5"/></button></div><p className="mt-4 text-[10px] font-bold">Sugestões populares</p><div className="mt-2 grid grid-cols-2 gap-2">{suggestions.map(s=><button key={s} onClick={()=>setQuery(s)} className="rounded-xl bg-white px-2 py-2.5 text-[9px] font-medium shadow-sm">{s}</button>)}</div></section><section className="mt-[190px] rounded-2xl border border-[#f3dfc4] bg-[#fffaf1] p-4"><p className="text-[11px] font-bold">💡 Dica MamaWise</p><p className="mt-2 text-[9px] leading-relaxed">Compare não só o preço, mas também frete, quantidade e preço por unidade para indicar o melhor custo-benefício.</p></section></>}
function Results({product,onBack,onAnalysis}:{product:string;onBack:()=>void;onAnalysis:()=>void}){return <><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold">{product}</p></div><button onClick={()=>{}} className="text-[9px] font-semibold text-success">Editar busca ✎</button></div><div className="mt-4 grid grid-cols-2 border-b border-border text-[10px] font-semibold"><button className="border-b-2 border-success pb-2 text-success">Melhor preço</button><button className="pb-2">Melhor custo-benefício</button></div><div className="mt-3 space-y-2.5">{offers.map((o,i)=><div key={o.name} className={`rounded-2xl border p-3.5 ${o.color}`}><div className="flex items-start gap-2"><span className="text-lg">{o.icon}</span><div className="flex-1"><p className="text-[10px] font-bold">{o.name}</p><p className="mt-1 text-lg font-bold text-[#17152b]">{brl(o.price)}</p><p className="text-[8px] text-muted-foreground">Frete: {brl(o.frete)}</p><p className="text-[9px] font-semibold">Total: {brl(o.total)}</p><p className="mt-1 text-[8px] text-muted-foreground">80 un. (R$ {(o.total/80).toFixed(2).replace(".",",")} por un.)</p><p className="text-[8px] text-muted-foreground">Entrega: {o.days} dias úteis</p><div className="flex justify-end"><a href={storeSearches[i]?.buildUrl(product)} target="_blank" rel="noreferrer"><Button className="mt-2 h-8 rounded-lg px-5 text-[9px]">Ver oferta</Button></a></div></div></div></div>)}</div><p className="mt-2 text-center text-[7px] text-muted-foreground">Preços e fretes são atualizados conforme a loja.</p><Button onClick={onAnalysis} className="mt-3 w-full rounded-xl text-[10px]">Ver análise da MamaWise <ChevronRight className="size-4"/></Button><button onClick={onBack} className="mx-auto mt-3 flex items-center gap-1 text-[9px] text-muted-foreground"><ArrowLeft className="size-3"/> Voltar</button></>}
function Analysis({onBack,onSave}:{onBack:()=>void;onSave:()=>void}){return <><section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#f7fff9] to-[#eefaf5] p-5 text-center"><span className="absolute left-4 top-4 text-xs">🎈</span><span className="absolute right-4 top-8 text-xs">✨</span><Trophy className="mx-auto size-7 text-[#e8a500]"/><p className="mt-2 text-[13px] font-bold text-success">Melhor custo-benefício</p><p className="mt-4 text-[10px] font-semibold">Mercado Livre</p><p className="mt-1 text-2xl font-bold text-success">R$ 89,80</p><p className="mt-1 text-[9px]">Total com frete</p><p className="mt-4 text-[11px] font-bold text-primary">R$ 1,12 por unidade</p><p className="mt-1 text-[8px] text-muted-foreground">Boa entrega e vendedor confiável.</p></section><section className="mt-3"><h2 className="text-[11px] font-bold">Comparativo final</h2>{offers.map((o,i)=><div key={o.name} className="mt-1.5 flex items-center gap-2 rounded-xl bg-white p-2.5 shadow-sm"><span>{i===0?"🏅":i===1?"🥈":"🥉"}</span><span className="flex-1 text-[9px] font-semibold">{o.name}</span><b className="text-[9px]">{brl(o.total)}</b><span className="text-[8px] text-muted-foreground">R$ {(o.total/80).toFixed(2).replace(".",",")}</span></div>)}</section><section className="mt-3 rounded-2xl bg-[#effbf4] p-4 text-center"><p className="text-[9px]">Você pode economizar</p><p className="text-[18px] font-bold text-success">até R$ 23,40</p><p className="text-[9px] font-semibold">escolhendo a melhor opção!</p></section><Button onClick={onSave} className="mt-3 w-full rounded-xl bg-success text-[10px] hover:bg-success">🐷 Guardar economia na Caixinha</Button><Button variant="outline" className="mt-2 w-full rounded-xl text-[9px]">Ver oferta no Mercado Livre</Button><button onClick={onBack} className="mx-auto mt-3 flex items-center gap-1 text-[9px] text-muted-foreground"><ArrowLeft className="size-3"/> Voltar</button></>}
