import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type FormEvent } from "react";
import { Search, CheckCircle2, AlertTriangle, XCircle, ExternalLink, PiggyBank, Sparkles, Store, ArrowRight, TrendingDown, ShoppingBag, Info, Lightbulb, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { MoneyInput } from "@/routes/planejamento";
import { expenseCategories } from "@/routes/gastos";
import { priorityLabel } from "@/components/PriorityBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useStore } from "@/lib/store";
import type { ExpenseCategory, Priority } from "@/lib/types";
import { analyzePurchase, brl, type AnalysisResult } from "@/lib/finance";
import { normalizeProductQuery, storeSearches } from "@/lib/ofertas";

export const Route = createFileRoute("/antes-de-comprar")({ head: () => ({ meta: [{ title: "Antes de comprar — Ninho Financeiro" }, { name: "description", content: "Pesquise um produto, compare lojas e avalie o impacto da compra no orçamento da família." }] }), component: AntesDeComprar });
const priorities: Priority[] = ["essencial", "importante", "pode_esperar"];
const verdictStyles = { ok: { box: "bg-success-soft", icon: <CheckCircle2 className="size-6 text-success" />, dot: "🟢" }, atencao: { box: "bg-warning-soft", icon: <AlertTriangle className="size-6 text-warning-foreground" />, dot: "🟡" }, risco: { box: "bg-danger-soft", icon: <XCircle className="size-6 text-destructive" />, dot: "🔴" } } as const;

function AntesDeComprar() {
  const { data, addAnalysis, addDeposit } = useStore();
  const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [category, setCategory] = useState<ExpenseCategory>("Outros"); const [priority, setPriority] = useState<Priority>("importante"); const [result, setResult] = useState<AnalysisResult | null>(null); const [searched, setSearched] = useState(false); const [yourPrice, setYourPrice] = useState(""); const [bestPrice, setBestPrice] = useState(""); const [savingMessage, setSavingMessage] = useState(""); const [savedBoxId, setSavedBoxId] = useState<string | null>(null);
  const normalizedName = useMemo(() => normalizeProductQuery(name), [name]); const economy = Math.max(0, Number(yourPrice) - Number(bestPrice)); const boxes = data.boxes;
  const smartAdvice = useMemo(() => { const high = Number(yourPrice); const best = Number(bestPrice); if (!normalizedName || !high || !best || best <= 0 || high <= 0) return null; const discount = high > best ? ((high - best) / high) * 100 : 0; const ratio = best / high; if (best > high) return { title: "O preço informado já parece melhor", text: `O valor de ${brl(high)} é menor que a oferta de ${brl(best)}. Antes de comprar, confirme frete e condições.`, level: "neutro" as const }; if (discount >= 20) return { title: "Boa oportunidade de economia", text: `A oferta está ${Math.round(discount)}% abaixo do preço mais alto informado. Se produto, quantidade e condições forem equivalentes, a diferença de ${brl(high - best)} merece atenção.`, level: "boa" as const }; if (discount >= 10) return { title: "Há uma economia interessante", text: `Você pode reduzir o gasto em ${brl(high - best)}. Confira se frete, prazo, quantidade e versão do produto são iguais.`, level: "boa" as const }; return { title: "Economia pequena", text: `A diferença é de ${brl(high - best)}. Vale considerar frete, prazo e qualidade antes de decidir.`, level: "atencao" as const }; }, [normalizedName, yourPrice, bestPrice]);
  function searchOffers() { if (!normalizedName) return; setSearched(true); setSavingMessage(""); setSavedBoxId(null); }
  function analyze(e: FormEvent) { e.preventDefault(); const value = Number(price); if (!value) return; const analysis = analyzePurchase(data, value, priority); setResult(analysis); addAnalysis({ productName: normalizedName || "Compra sem nome", price: value, category, priority, verdict: analysis.verdict, percentOfAvailable: analysis.percentOfAvailable, remainingAfter: analysis.remainingAfter }); }
  function saveSavings() { if (!economy) return; if (!boxes.length) { setSavingMessage(`Você economizou ${brl(economy)}. Crie uma Caixinha do Futuro para transformar essa economia em uma reserva.`); return; } setSavingMessage(`Você economizou ${brl(economy)}. Escolha uma caixinha abaixo para registrar esse valor.`); }
  function addToBox(boxId: string) { if (!economy || savedBoxId) return; const box = boxes.find((item) => item.id === boxId); if (!box) return; addDeposit({ boxId, amount: economy, date: new Date().toISOString().slice(0, 10), note: `Economia na compra de ${normalizedName || "produto"}` }); setSavedBoxId(boxId); setSavingMessage(`${brl(economy)} foi registrado na Caixinha de ${box.childName}. ❤️`); }
  return <AppShell title="Antes de comprar" subtitle="Pesquise, compare e pense antes de gastar.">
    <section className="card-premium p-5 sm:p-6">
      <div className="mb-5 flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ShoppingBag className="size-5" /></div><div><h2 className="font-display text-xl font-semibold">Encontre o melhor preço</h2><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Digite o produto e pesquise nas principais lojas. O MamaWise não inventa preços: você confere a oferta atual diretamente na loja.</p></div></div>
      <div className="flex flex-col gap-3 sm:flex-row"><Input className="h-12 rounded-2xl" placeholder="Ex.: carrinho de bebê, fralda tamanho M" value={name} onChange={(e) => setName(e.target.value)} onKeyDown={(e) => e.key === "Enter" && searchOffers()} /><Button type="button" onClick={searchOffers} disabled={!normalizedName} size="lg" className="h-12 rounded-2xl sm:px-7"><Search className="mr-2 size-4" /> Pesquisar</Button></div>
      {searched && <div className="mt-5 rounded-3xl bg-muted/60 p-4 sm:p-5"><div className="flex items-start gap-3"><Store className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-semibold">Pesquisas para “{normalizedName}”</p><p className="mt-1 text-sm text-muted-foreground">Abra uma opção para ver os resultados atuais. O MamaWise não apresenta preços inventados.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{storeSearches.map((store) => <a key={store.name} href={store.buildUrl(normalizedName)} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-3 rounded-2xl border border-border bg-card p-4 transition-colors hover:bg-muted"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Store className="size-4" /></span><div><p className="font-semibold text-foreground">{store.name}</p><p className="mt-1 text-xs text-muted-foreground">{store.description}</p></div></div><ExternalLink className="size-4 shrink-0 text-muted-foreground group-hover:text-primary" /></a>)}</div><div className="mt-4 flex gap-2 rounded-2xl border border-border bg-card p-3 text-xs text-muted-foreground"><Info className="size-4 shrink-0" /> Os preços e condições podem mudar. Confirme o valor, frete e prazo antes de comprar.</div></div>}
    </section>
    <section className="card-premium mt-6 p-5 sm:p-6"><div className="mb-5 flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-primary-soft text-primary"><Sparkles className="size-5" /></div><div><h2 className="font-display text-xl font-semibold">Análise inteligente da compra</h2><p className="mt-1 text-sm text-muted-foreground">O MamaWise interpreta os preços que você informou e ajuda a decidir com mais segurança.</p></div></div>{smartAdvice ? <div className={`rounded-3xl p-5 ${smartAdvice.level === "boa" ? "bg-success-soft" : smartAdvice.level === "atencao" ? "bg-warning-soft" : "bg-muted/60"}`}><div className="flex items-start gap-3"><Lightbulb className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-semibold text-foreground">{smartAdvice.title}</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{smartAdvice.text}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-card/80 p-3"><p className="text-xs text-muted-foreground">Preço informado</p><p className="mt-1 font-semibold">{brl(Number(yourPrice))}</p></div><div className="rounded-2xl bg-card/80 p-3"><p className="text-xs text-muted-foreground">Melhor preço</p><p className="mt-1 font-semibold">{brl(Number(bestPrice))}</p></div><div className="rounded-2xl bg-card/80 p-3"><p className="text-xs text-muted-foreground">Economia</p><p className="mt-1 font-semibold text-success">{brl(economy)}</p></div></div><div className="mt-4 flex items-start gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 shrink-0" /> A análise não garante que a oferta seja realmente melhor: confirme modelo, quantidade, frete, prazo e vendedor.</div></div> : <div className="rounded-3xl border border-dashed border-border p-5 text-sm text-muted-foreground">Informe o produto e os dois preços abaixo para receber uma orientação automática.</div>}</section>
    <section className="card-premium mt-6 p-5 sm:p-6"><div className="mb-5 flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-success-soft text-success"><TrendingDown className="size-5" /></div><div><h2 className="font-display text-xl font-semibold">Transforme uma economia em reserva</h2><p className="mt-1 text-sm text-muted-foreground">Informe os dois preços para descobrir quanto você poderia economizar.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="preco-encontrado">Preço mais alto</Label><MoneyInput id="preco-encontrado" value={yourPrice} onChange={setYourPrice} /></div><div className="flex flex-col gap-2"><Label htmlFor="melhor-preco">Melhor preço</Label><MoneyInput id="melhor-preco" value={bestPrice} onChange={setBestPrice} /></div></div>{economy > 0 && <div className="mt-5 rounded-3xl bg-success-soft p-5"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Economia encontrada</p><p className="mt-1 text-3xl font-bold text-success">{brl(economy)}</p></div><PiggyBank className="size-9 text-success" /></div><p className="mt-2 text-sm text-muted-foreground">Em vez de gastar essa diferença, você pode transformar a economia em uma reserva para seu filho.</p><Button size="lg" className="mt-4 h-12 rounded-2xl" onClick={saveSavings} disabled={!!savedBoxId}><PiggyBank className="mr-2 size-5" /> {savedBoxId ? "Economia registrada" : "Guardar essa economia"}</Button></div>}{savingMessage && <p className="mt-4 rounded-2xl bg-primary-soft px-4 py-3 text-sm text-primary">{savingMessage}</p>}{economy > 0 && boxes.length > 0 && !savedBoxId && <div className="mt-4 rounded-3xl border border-border p-4"><p className="mb-3 text-sm font-semibold">Escolha onde guardar</p><div className="grid gap-2 sm:grid-cols-2">{boxes.map((box) => <Button key={box.id} variant="outline" className="h-auto justify-between rounded-2xl px-4 py-3 text-left" onClick={() => addToBox(box.id)}><span>Caixinha de {box.childName}</span><ArrowRight className="size-4" /></Button>)}</div></div>}</section>
    <form onSubmit={analyze} className="card-premium mt-6 p-5 sm:p-6"><div className="mb-5 flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-secondary text-primary"><Sparkles className="size-5" /></div><div><h2 className="font-display text-xl font-semibold">Veja se a compra cabe no orçamento</h2><p className="mt-1 text-sm text-muted-foreground">A análise considera seu saldo disponível e a prioridade da compra.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="preco-compra">Preço</Label><MoneyInput id="preco-compra" value={price} onChange={setPrice} /></div><div className="flex flex-col gap-2"><Label>Categoria</Label><Select value={category} onValueChange={(v) => setCategory(v as ExpenseCategory)}><SelectTrigger className="h-12 w-full rounded-2xl"><SelectValue /></SelectTrigger><SelectContent>{expenseCategories.map((c) => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Prioridade</Label><Select value={priority} onValueChange={(v) => setPriority(v as Priority)}><SelectTrigger className="h-12 w-full rounded-2xl"><SelectValue /></SelectTrigger><SelectContent>{priorities.map((p) => <SelectItem key={p} value={p}>{priorityLabel[p]}</SelectItem>)}</SelectContent></Select></div></div><Button type="submit" size="lg" className="mt-6 h-12 w-full rounded-2xl text-base sm:w-auto sm:px-8">Ver análise financeira</Button></form>
    {result ? <section className={`mt-6 rounded-3xl border border-border p-5 sm:p-6 ${verdictStyles[result.verdict].box}`}><p className="text-xs font-semibold tracking-widest text-muted-foreground uppercase">Resultado</p><div className="mt-3 flex items-center gap-3"><span>{verdictStyles[result.verdict].icon}</span><h2 className="font-display text-xl font-semibold">{verdictStyles[result.verdict].dot} {result.headline}</h2></div><ul className="mt-5 flex flex-col gap-3">{result.explanation.map((line) => <li key={line} className="rounded-2xl bg-card/80 px-4 py-3 text-sm leading-relaxed">{line}</li>)}</ul><div className="mt-4 h-2.5 w-full overflow-hidden rounded-full bg-card"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, Math.round(result.percentOfAvailable))}%` }} /></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Esta é uma ferramenta de organização financeira e não é aconselhamento financeiro profissional.</p></section> : <p className="mt-6 rounded-3xl border border-dashed border-border bg-card px-5 py-8 text-center text-sm text-muted-foreground">Informe o preço para analisar o impacto da compra nos seus {brl(data.financial.availableBalance)} disponíveis.</p>}
  </AppShell>;
}
