import { createFileRoute } from "@tanstack/react-router";
import { Settings, ArrowUp, ArrowDown, Target, Coins, Heart } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { useStore } from "@/lib/store";
import { boxStats, depositsOf } from "@/lib/caixinha";
import { brl } from "@/lib/finance";

export const Route = createFileRoute("/caixinha")({ head: () => ({ meta: [{ title: "Caixinha do seu filho — MamaWise" }] }), component: Caixinha });

function Caixinha() {
  const { data, addBox, addDeposit } = useStore();
  const [depositOpen, setDepositOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [value, setValue] = useState("");
  const box = data.boxes[0]; const stats = box ? boxStats(box, data.deposits) : null; const history = box ? depositsOf(data.deposits, box.id) : [];
  function deposit() { const n = Number(value); if (!box || !n || n <= 0) { toast.error("Informe um valor maior que zero."); return; } addDeposit({ boxId: box.id, amount: n, date: new Date().toISOString().slice(0, 10), note: "Depósito" }); toast.success("Valor guardado!", { description: `${brl(n)} adicionados à sua caixinha.` }); setValue(""); setDepositOpen(false); }
  return <AppShell title="Caixinha do seu filho">
    <div className="space-y-3">
      <div className="flex justify-end"><button className="grid size-9 place-items-center rounded-xl bg-white text-muted-foreground shadow-sm" aria-label="Configurações"><Settings className="size-4" /></button></div>
      {!box ? <section className="rounded-[28px] bg-gradient-to-br from-[#6d35e8] to-[#9858e8] p-6 text-white shadow-[0_18px_38px_rgba(104,54,190,.22)]"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-white/75">Seu primeiro passo</p><p className="mt-3 text-[24px] font-bold">Comece a guardar para o futuro.</p><p className="mt-2 text-[10px] leading-relaxed text-white/75">Crie uma meta para seu filho e acompanhe cada conquista.</p><Button onClick={() => setCreateOpen(true)} className="mt-5 h-11 w-full rounded-xl bg-white text-primary hover:bg-white/90">Criar minha caixinha</Button></section> : <>
        <section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#6d35e8] via-[#7c45df] to-[#9a59e8] p-5 text-white shadow-[0_18px_38px_rgba(104,54,190,.22)]"><div className="relative z-10 pr-24"><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-white/75">Caixinha do futuro</p><p className="mt-2 text-[29px] font-bold tracking-tight">{brl(stats?.current ?? 0)}</p><div className="mt-3 flex items-center justify-between text-[9px] text-white/80"><span>{Math.round(stats?.percent ?? 0)}% da meta</span><span>Meta {brl(stats?.target ?? 0)}</span></div><Progress value={stats?.percent ?? 0} className="mt-1.5 h-2 bg-white/20 [&>div]:bg-white" /></div><div className="pointer-events-none absolute bottom-1 right-2 z-20 flex h-[72px] w-[72px] items-end justify-center text-[58px] leading-none">🐷</div><Heart className="absolute right-5 top-5 z-20 size-4 fill-white/20 text-white/60" /></section>
        <div className="grid grid-cols-3 gap-2"><Action icon={<ArrowUp className="size-4" />} label="Depositar" onClick={() => setDepositOpen(true)} tone="green" /><Action icon={<ArrowDown className="size-4" />} label="Retirar" onClick={() => toast.info("A Caixinha registra o planejamento; nenhum dinheiro real é movimentado.")} tone="pink" /><Action icon={<Target className="size-4" />} label="Meta" onClick={() => toast.info(`Sua meta atual é ${brl(stats?.target ?? 0)}.`)} tone="purple" /></div>
        <section className="rounded-[24px] border border-border bg-white p-4 shadow-[0_6px_20px_rgba(35,25,55,.04)]"><div className="flex items-center justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.08em] text-muted-foreground">Seu progresso</p><h2 className="mt-1 text-[15px] font-bold">Meta do seu filho</h2></div><span className="text-[11px] font-bold text-primary">{Math.round(stats?.percent ?? 0)}%</span></div><p className="mt-2 text-[9px] text-muted-foreground">Faltam <b className="text-foreground">{brl(stats?.remaining ?? 0)}</b> para alcançar sua meta.</p><div className="mt-3 h-2.5 rounded-full bg-[#eeeaf4]"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, stats?.percent ?? 0)}%` }} /></div><div className="mt-1.5 flex justify-between text-[8px] text-muted-foreground"><span>Começo</span><span>Meta</span></div></section>
        <section className="rounded-[24px] border border-border bg-white p-4 shadow-[0_6px_20px_rgba(35,25,55,.04)]"><div className="flex items-center justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.08em] text-muted-foreground">Movimentações</p><h2 className="mt-1 text-[15px] font-bold">Histórico</h2></div><Coins className="size-4 text-primary" /></div><div className="mt-2 divide-y divide-border">{history.slice(0, 5).map(d => <div key={d.id} className="flex items-center gap-3 py-2.5"><span className="grid size-8 place-items-center rounded-xl bg-[#eaf8f0] text-success"><Coins className="size-3.5" /></span><div className="flex-1"><p className="text-[9px] font-semibold">{d.note || "Depósito"}</p><p className="text-[8px] text-muted-foreground">{new Date(d.date + "T00:00:00").toLocaleDateString("pt-BR")}</p></div><b className="text-[9px] text-success">+ {brl(d.amount)}</b></div>)}</div>{history.length === 0 && <p className="py-4 text-center text-[9px] text-muted-foreground">Nenhum depósito registrado ainda.</p>}</section>
      </>}
      <Dialog open={depositOpen} onOpenChange={setDepositOpen}><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>Depositar na Caixinha</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Valor</Label><Input inputMode="decimal" value={value} onChange={e => setValue(e.target.value.replace(",", "."))} placeholder="100" /></div><Button onClick={deposit} className="w-full">Guardar dinheiro</Button></div></DialogContent></Dialog>
      <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>Criar Caixinha do Futuro</DialogTitle></DialogHeader><Create onCreate={box => { addBox(box); setCreateOpen(false); }} /></DialogContent></Dialog>
    </div>
  </AppShell>;
}
function Action({ icon, label, onClick, tone }: { icon: React.ReactNode; label: string; onClick: () => void; tone: "green" | "pink" | "purple" }) { const bg = tone === "green" ? "bg-[#effbf4] text-success" : tone === "pink" ? "bg-[#fff2f6] text-destructive" : "bg-[#f5efff] text-primary"; return <button onClick={onClick} className={`flex min-h-[72px] flex-col items-center justify-center gap-2 rounded-2xl border border-transparent text-[9px] font-bold shadow-sm transition-transform hover:-translate-y-0.5 ${bg}`}>{icon}{label}</button>; }
function Create({ onCreate }: { onCreate: (v: Parameters<ReturnType<typeof useStore>["addBox"]>[0]) => void }) { const [name, setName] = useState(""); const [target, setTarget] = useState(""); return <form onSubmit={e => { e.preventDefault(); const n = Number(target); if (!name.trim() || !n) { toast.error("Informe nome e meta."); return; } onCreate({ childName: name.trim(), objective: "futuro_bebe", initialAmount: 0, target: n, monthlyContribution: 0 }); toast.success("Caixinha criada!"); }} className="space-y-4"><div><Label>Nome da criança</Label><Input value={name} onChange={e => setName(e.target.value)} placeholder="Ex.: Miguel" /></div><div><Label>Meta</Label><Input inputMode="decimal" value={target} onChange={e => setTarget(e.target.value.replace(",", "."))} placeholder="2000" /></div><Button type="submit" className="w-full">Criar caixinha</Button></form>; }
