import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { BoxObjective, SavingsBox } from "@/lib/types";
import { objectives } from "@/lib/caixinha";
import { brl } from "@/lib/finance";

type Values = { childName: string; childBirthDate: string; objective: BoxObjective; customObjective: string; target: string; monthlyContribution: string; targetDate: string };

export function EditBoxDialog({ box, open, onOpenChange, onSave }: { box: SavingsBox | null; open: boolean; onOpenChange: (open: boolean) => void; onSave: (id: string, patch: Partial<SavingsBox>) => void }) {
  const [values, setValues] = useState<Values>({ childName: "", childBirthDate: "", objective: "futuro_bebe", customObjective: "", target: "", monthlyContribution: "", targetDate: "" });
  useEffect(() => { if (box) setValues({ childName: box.childName, childBirthDate: box.childBirthDate ?? "", objective: box.objective, customObjective: box.customObjective ?? "", target: String(box.target), monthlyContribution: String(box.monthlyContribution), targetDate: box.targetDate ?? "" }); }, [box]);
  function set<K extends keyof Values>(key: K, value: Values[K]) { setValues((prev) => ({ ...prev, [key]: value })); }
  function save(e: FormEvent) { e.preventDefault(); if (!box) return; const target = Number(values.target); const monthlyContribution = Number(values.monthlyContribution) || 0; if (!values.childName.trim() || !Number.isFinite(target) || target <= 0) { toast.error("Informe o nome e uma meta maior que zero."); return; } if (target < box.initialAmount) { toast.error(`A nova meta não pode ficar abaixo do valor já guardado de ${brl(box.initialAmount)}.`); return; } onSave(box.id, { childName: values.childName.trim(), childBirthDate: values.childBirthDate || undefined, objective: values.objective, customObjective: values.objective === "outro" ? values.customObjective.trim() || undefined : undefined, target, monthlyContribution: Math.max(0, monthlyContribution), targetDate: values.targetDate || undefined } as Partial<SavingsBox>); toast.success("Caixinha atualizada!"); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] overflow-y-auto rounded-3xl sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl">Editar Caixinha do Futuro</DialogTitle></DialogHeader>{box ? <form onSubmit={save} className="flex flex-col gap-5"><div className="rounded-2xl bg-primary-soft p-4"><p className="text-sm font-medium text-foreground">✏️ Ajuste sua meta</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Você pode mudar os dados da caixinha sem apagar o histórico de depósitos.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="edit-child-name">Nome da criança</Label><Input id="edit-child-name" className="h-12 rounded-2xl" value={values.childName} onChange={(e) => set("childName", e.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-child-birth">Data de nascimento</Label><Input id="edit-child-birth" type="date" className="h-12 rounded-2xl" value={values.childBirthDate} onChange={(e) => set("childBirthDate", e.target.value)} /></div></div><div className="flex flex-col gap-2"><Label htmlFor="edit-objective">Objetivo</Label><select id="edit-objective" className="h-12 rounded-2xl border border-border bg-background px-4 text-sm" value={values.objective} onChange={(e) => set("objective", e.target.value as BoxObjective)}>{objectives.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div>{values.objective === "outro" ? <div className="flex flex-col gap-2"><Label htmlFor="edit-custom-objective">Qual é o objetivo?</Label><Input id="edit-custom-objective" className="h-12 rounded-2xl" value={values.customObjective} onChange={(e) => set("customObjective", e.target.value)} /></div> : null}<div className="grid gap-4 sm:grid-cols-3"><div className="flex flex-col gap-2"><Label htmlFor="edit-target">Meta</Label><Input id="edit-target" inputMode="decimal" className="h-12 rounded-2xl" value={values.target} onChange={(e) => set("target", e.target.value.replace(/[^\d.,]/g, "").replace(",", "."))} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-monthly">Por mês</Label><Input id="edit-monthly" inputMode="decimal" className="h-12 rounded-2xl" value={values.monthlyContribution} onChange={(e) => set("monthlyContribution", e.target.value.replace(/[^\d.,]/g, "").replace(",", "."))} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-target-date">Meta até</Label><Input id="edit-target-date" type="date" className="h-12 rounded-2xl" value={values.targetDate} onChange={(e) => set("targetDate", e.target.value)} /></div></div><Button type="submit" size="lg" className="h-12 rounded-2xl text-base"><CheckCircle2 className="size-5" /> Salvar alterações</Button></form> : null}</DialogContent></Dialog>;
}
