import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { BoxObjective, SavingsBox } from "@/lib/types";
import { objectives } from "@/lib/caixinha";
import { brl } from "@/lib/finance";

type Values = { childName: string; birthDate: string; objective: BoxObjective; customObjective: string; target: string; monthly: string; targetDate: string };

export function EditBoxDialog({ box, open, onOpenChange, onSave }: { box: SavingsBox | null; open: boolean; onOpenChange: (open: boolean) => void; onSave: (id: string, patch: Partial<SavingsBox>) => void }) {
  const [values, setValues] = useState<Values>({ childName: "", birthDate: "", objective: "futuro_bebe", customObjective: "", target: "", monthly: "", targetDate: "" });
  useEffect(() => { if (box) setValues({ childName: box.childName, birthDate: box.birthDate ?? "", objective: box.objective, customObjective: box.customObjective ?? "", target: String(box.target), monthly: String(box.monthly), targetDate: box.targetDate ?? "" }); }, [box]);
  function set<K extends keyof Values>(key: K, value: Values[K]) { setValues((prev) => ({ ...prev, [key]: value })); }
  function save(e: FormEvent) { e.preventDefault(); if (!box) return; const target = Number(values.target); const monthly = Number(values.monthly) || 0; if (!values.childName.trim() || !Number.isFinite(target) || target <= 0) { toast.error("Informe o nome e uma meta maior que zero."); return; } if (target < box.target && target < box.initialAmount) { toast.error(`A nova meta não pode ficar abaixo do valor inicial de ${brl(box.initialAmount)}.`); return; } onSave(box.id, { childName: values.childName.trim(), birthDate: values.birthDate || undefined, objective: values.objective, customObjective: values.objective === "outro" ? values.customObjective.trim() : undefined, target, monthly: Math.max(0, monthly), targetDate: values.targetDate || undefined }); toast.success("Caixinha atualizada!"); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="rounded-3xl sm:max-w-lg"><DialogHeader><DialogTitle>Editar caixinha</DialogTitle></DialogHeader>{box ? <form onSubmit={save} className="flex flex-col gap-4"><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="edit-child">Nome da criança</Label><Input id="edit-child" className="h-12 rounded-2xl" value={values.childName} onChange={(e) => set("childName", e.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-birth">Nascimento</Label><Input id="edit-birth" type="date" className="h-12 rounded-2xl" value={values.birthDate} onChange={(e) => set("birthDate", e.target.value)} /></div></div><div className="flex flex-col gap-2"><Label htmlFor="edit-objective">Objetivo</Label><select id="edit-objective" className="h-12 rounded-2xl border border-border bg-background px-4 text-sm" value={values.objective} onChange={(e) => set("objective", e.target.value as BoxObjective)}>{objectives.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div>{values.objective === "outro" ? <div className="flex flex-col gap-2"><Label htmlFor="edit-custom">Qual objetivo?</Label><Input id="edit-custom" className="h-12 rounded-2xl" value={values.customObjective} onChange={(e) => set("customObjective", e.target.value)} /></div> : null}<div className="grid gap-4 sm:grid-cols-3"><div className="flex flex-col gap-2"><Label htmlFor="edit-target">Meta</Label><Input id="edit-target" inputMode="decimal" className="h-12 rounded-2xl" value={values.target} onChange={(e) => set("target", e.target.value.replace(/[^\d.,]/g, "").replace(",", "."))} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-monthly">Por mês</Label><Input id="edit-monthly" inputMode="decimal" className="h-12 rounded-2xl" value={values.monthly} onChange={(e) => set("monthly", e.target.value.replace(/[^\d.,]/g, "").replace(",", "."))} /></div><div className="flex flex-col gap-2"><Label htmlFor="edit-date">Meta até</Label><Input id="edit-date" type="date" className="h-12 rounded-2xl" value={values.targetDate} onChange={(e) => set("targetDate", e.target.value)} /></div></div><Button type="submit" size="lg" className="h-12 rounded-2xl"><CheckCircle2 className="size-5" /> Salvar alterações</Button></form> : null}</DialogContent></Dialog>;
}
