/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Kept synchronized for the new MamaWise screens.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntesDeComprarRouteImport } from './routes/antes-de-comprar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaixinhaRouteImport } from './routes/caixinha'
import { Route as EnxovalRouteImport } from './routes/enxoval'
import { Route as FilhoRouteImport } from './routes/filho'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PremiumRouteImport } from './routes/premium'

const IndexRoute = IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const AntesDeComprarRoute = AntesDeComprarRouteImport.update({id:'/antes-de-comprar',path:'/antes-de-comprar',getParentRoute:()=>rootRouteImport} as any)
const AuthRoute = AuthRouteImport.update({id:'/auth',path:'/auth',getParentRoute:()=>rootRouteImport} as any)
const CaixinhaRoute = CaixinhaRouteImport.update({id:'/caixinha',path:'/caixinha',getParentRoute:()=>rootRouteImport} as any)
const EnxovalRoute = EnxovalRouteImport.update({id:'/enxoval',path:'/enxoval',getParentRoute:()=>rootRouteImport} as any)
const FilhoRoute = FilhoRouteImport.update({id:'/filho',path:'/filho',getParentRoute:()=>rootRouteImport} as any)
const AssistenteRoute = AssistenteRouteImport.update({id:'/assistente',path:'/assistente',getParentRoute:()=>rootRouteImport} as any)
const GastosRoute = GastosRouteImport.update({id:'/gastos',path:'/gastos',getParentRoute:()=>rootRouteImport} as any)
const MaisRoute = MaisRouteImport.update({id:'/mais',path:'/mais',getParentRoute:()=>rootRouteImport} as any)
const MetasRoute = MetasRouteImport.update({id:'/metas',path:'/metas',getParentRoute:()=>rootRouteImport} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({id:'/planejamento',path:'/planejamento',getParentRoute:()=>rootRouteImport} as any)
const PremiumRoute = PremiumRouteImport.update({id:'/premium',path:'/premium',getParentRoute:()=>rootRouteImport} as any)

export interface FileRoutesByFullPath {'/':typeof IndexRoute;'/antes-de-comprar':typeof AntesDeComprarRoute;'/auth':typeof AuthRoute;'/caixinha':typeof CaixinhaRoute;'/enxoval':typeof EnxovalRoute;'/filho':typeof FilhoRoute;'/assistente':typeof AssistenteRoute;'/gastos':typeof GastosRoute;'/mais':typeof MaisRoute;'/metas':typeof MetasRoute;'/planejamento':typeof PlanejamentoRoute;'/premium':typeof PremiumRoute}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {__root__:typeof rootRouteImport;'/':typeof IndexRoute;'/antes-de-comprar':typeof AntesDeComprarRoute;'/auth':typeof AuthRoute;'/caixinha':typeof CaixinhaRoute;'/enxoval':typeof EnxovalRoute;'/filho':typeof FilhoRoute;'/assistente':typeof AssistenteRoute;'/gastos':typeof GastosRoute;'/mais':typeof MaisRoute;'/metas':typeof MetasRoute;'/planejamento':typeof PlanejamentoRoute;'/premium':typeof PremiumRoute}
export interface FileRouteTypes {fileRoutesByFullPath:FileRoutesByFullPath;fullPaths:keyof FileRoutesByFullPath;fileRoutesByTo:FileRoutesByTo;to:keyof FileRoutesByTo;id:keyof FileRoutesById;fileRoutesById:FileRoutesById}
export interface RootRouteChildren {IndexRoute:typeof IndexRoute;AntesDeComprarRoute:typeof AntesDeComprarRoute;AuthRoute:typeof AuthRoute;CaixinhaRoute:typeof CaixinhaRoute;EnxovalRoute:typeof EnxovalRoute;FilhoRoute:typeof FilhoRoute;AssistenteRoute:typeof AssistenteRoute;GastosRoute:typeof GastosRoute;MaisRoute:typeof MaisRoute;MetasRoute:typeof MetasRoute;PlanejamentoRoute:typeof PlanejamentoRoute;PremiumRoute:typeof PremiumRoute}

declare module '@tanstack/react-router' { interface FileRoutesByPath { '/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport}; '/antes-de-comprar':{id:'/antes-de-comprar';path:'/antes-de-comprar';fullPath:'/antes-de-comprar';preLoaderRoute:typeof AntesDeComprarRouteImport;parentRoute:typeof rootRouteImport}; '/auth':{id:'/auth';path:'/auth';fullPath:'/auth';preLoaderRoute:typeof AuthRouteImport;parentRoute:typeof rootRouteImport}; '/caixinha':{id:'/caixinha';path:'/caixinha';fullPath:'/caixinha';preLoaderRoute:typeof CaixinhaRouteImport;parentRoute:typeof rootRouteImport}; '/enxoval':{id:'/enxoval';path:'/enxoval';fullPath:'/enxoval';preLoaderRoute:typeof EnxovalRouteImport;parentRoute:typeof rootRouteImport}; '/filho':{id:'/filho';path:'/filho';fullPath:'/filho';preLoaderRoute:typeof FilhoRouteImport;parentRoute:typeof rootRouteImport}; '/assistente':{id:'/assistente';path:'/assistente';fullPath:'/assistente';preLoaderRoute:typeof AssistenteRouteImport;parentRoute:typeof rootRouteImport}; '/gastos':{id:'/gastos';path:'/gastos';fullPath:'/gastos';preLoaderRoute:typeof GastosRouteImport;parentRoute:typeof rootRouteImport}; '/mais':{id:'/mais';path:'/mais';fullPath:'/mais';preLoaderRoute:typeof MaisRouteImport;parentRoute:typeof rootRouteImport}; '/metas':{id:'/metas';path:'/metas';fullPath:'/metas';preLoaderRoute:typeof MetasRouteImport;parentRoute:typeof rootRouteImport}; '/planejamento':{id:'/planejamento';path:'/planejamento';fullPath:'/planejamento';preLoaderRoute:typeof PlanejamentoRouteImport;parentRoute:typeof rootRouteImport}; '/premium':{id:'/premium';path:'/premium';fullPath:'/premium';preLoaderRoute:typeof PremiumRouteImport;parentRoute:typeof rootRouteImport} } }

const rootRouteChildren:RootRouteChildren={IndexRoute,AntesDeComprarRoute,AuthRoute,CaixinhaRoute,EnxovalRoute,FilhoRoute,AssistenteRoute,GastosRoute,MaisRoute,MetasRoute,PlanejamentoRoute,PremiumRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register {ssr:true;router:Awaited<ReturnType<typeof getRouter>>;config:Awaited<ReturnType<typeof startInstance.getOptions>>} }
